version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: LLMSessionGateway.API/Dockerfile
    image: llmsessiongateway-api:latest
    ports:
      - "5000:8080"  
    restart: unless-stopped

