apiVersion: v1
kind: Secret
metadata:
  name: llmsgw-secrets
  namespace: llmsessiongateway
type: Opaque
stringData:
  APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=00000000-0000-0000-0000-000000000000
  AZURE_REDIS_CONNECTION_STRING=localhost:6379,password=Passw0rd123!,ssl=False,abortConnect=False
  AZURE_CLIENT_ID=11111111-1111-1111-1111-111111111111
  AZURE_MANAGED_IDENTITY_RESOURCE_ID=/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/dummy-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dummy-mi
  PFX_B64=U29tZUR1bW15QmFzZTY0Q29udGVudA==
  PFX_PWD=DummyPassword123!